version: '3'
services:
  db:
    container_name: enlabs_assignment_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresPass
      - POSTGRES_DB=enlabs
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - ./_db:/var/lib/postgresql/data
  app:
    container_name: enlabs_assignment_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: ["./wait-for-it.sh", "-s" ,"-t", "20", "enlabs_assignment_db:5432", "--"]
    command: ["./_dist/app"]
    ports:
      - '8080:8080'
